# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

_admin_client:
    resource: "@WellCommerceAppBundle/Resources/config/routing/client/admin.yml"
    prefix: /admin/client

_admin_client_group:
    resource: "@WellCommerceAppBundle/Resources/config/routing/client_group/admin.yml"
    prefix: /admin/client/group

_admin_company:
    resource: "@WellCommerceAppBundle/Resources/config/routing/company/admin.yml"
    prefix: /admin/configuration/company

_admin_currency:
    resource: "@WellCommerceAppBundle/Resources/config/routing/currency/admin.yml"
    prefix: /admin/configuration/currency

_admin_dashboard:
    resource: "@WellCommerceAppBundle/Resources/config/routing/dashboard/admin.yml"
    prefix: /admin/dashboard

_admin_dictionary:
    resource: "@WellCommerceAppBundle/Resources/config/routing/dictionary/admin.yml"
    prefix: /admin/configuration/dictionary

_admin_layout_box:
    resource: "@WellCommerceAppBundle/Resources/config/routing/layout_box/admin.yml"
    prefix: /admin/layout/box

_admin_locale:
    resource: "@WellCommerceAppBundle/Resources/config/routing/locale/admin.yml"
    prefix: /admin/configuration/locale

_admin_media:
    resource: "@WellCommerceAppBundle/Resources/config/routing/media/admin.yml"
    prefix: /admin/media

_admin_package:
    resource: "@WellCommerceAppBundle/Resources/config/routing/package/admin.yml"
    prefix: /admin/package

_admin_shop:
    resource: "@WellCommerceAppBundle/Resources/config/routing/shop/admin.yml"
    prefix: /admin/configuration/shop

_admin_tax:
    resource: "@WellCommerceAppBundle/Resources/config/routing/tax/admin.yml"
    prefix: /admin/configuration/tax

_admin_theme:
    resource: "@WellCommerceAppBundle/Resources/config/routing/theme/admin.yml"
    prefix: /admin/layout/theme

_admin_user:
    resource: "@WellCommerceAppBundle/Resources/config/routing/user/admin.yml"
    prefix: /admin/user

_admin_user_group:
    resource: "@WellCommerceAppBundle/Resources/config/routing/user_group/admin.yml"
    prefix: /admin/user/group

_front_client:
    resource: "@WellCommerceAppBundle/Resources/config/routing/client/front.yml"
    prefix: /client

_front_currency:
    resource: "@WellCommerceAppBundle/Resources/config/routing/currency/front.yml"
    prefix: /currency

_front_locale:
    resource: "@WellCommerceAppBundle/Resources/config/routing/locale/front.yml"
    prefix: /locale

_front_wishlist:
    resource: "@WellCommerceWishlistBundle/Resources/config/routing.yml"

front.home_page.index:
    path: /
    defaults:
        _controller: 'web.home_page.controller.front:indexAction'

KCFinder_browse:
    path:  /admin/kcfinder/{file}
    options:
        expose: true
    defaults:
        _controller: "IkadocKCFinderBundle:Proxy:proxy"
    requirements:
        file: "favico\\.ico|browse\\.php|js_localize\\.php|upload\\.php|css/index\\.php|js/index\\.php|themes/[^\\.]*/css\\.php|themes/[^\\.]*/js\\.php|themes/[^\\.]*/img/[^\\.]*\\.(png|gif|jpg)"

root:
    path: /admin
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: admin.user.index
        permanent: false

remove_trailing_slash:
    path: /{url}
    defaults: { _controller: WellCommerceAppBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]
