# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

imports:
    - { resource: 'services/breadcrumb.yml' }
    - { resource: 'services/datagrid.yml' }
    - { resource: 'services/dataset.yml' }
    - { resource: 'services/doctrine.yml' }
    - { resource: 'services/form.yml' }
    - { resource: 'services/layout.yml' }
    - { resource: 'services/routing.yml' }

services:
    flash.helper:
        class: WellCommerce\Bundle\CoreBundle\Helper\Flash\FlashHelper
        arguments: ['@session', '@translator.helper']

    image.helper:
        class: WellCommerce\Bundle\CoreBundle\Helper\Image\ImageHelper
        arguments: ['@liip_imagine.cache.manager', '@liip_imagine.filter.configuration']

    request.helper:
        class: WellCommerce\Bundle\CoreBundle\Helper\Request\RequestHelper
        arguments: ['@request_stack','%locale%']

    process.helper:
        class: WellCommerce\Bundle\CoreBundle\Helper\Process\ProcessHelper
        arguments: ['%php_bin_path%', '%kernel.root_dir%/../']

    validator.helper:
        class: WellCommerce\Bundle\CoreBundle\Helper\Validator\ValidatorHelper
        arguments: ['@validator']

    translator.helper:
        class: WellCommerce\Bundle\CoreBundle\Helper\Translator\TranslatorHelper
        autowire: true

    templating.helper:
        class: WellCommerce\Bundle\CoreBundle\Helper\Templating\TemplatingHelper
        arguments: ['@templating', '@kernel', '@twig']

    mailer.helper:
        class: WellCommerce\Bundle\CoreBundle\Helper\Mailer\MailerHelper
        arguments: ['@templating.helper', '@validator.helper', '%kernel.debug%']

    security.helper:
        class: WellCommerce\Bundle\CoreBundle\Helper\Security\SecurityHelper
        arguments: ['@security.token_storage', '@request.helper']

    twig.extension.image:
        class: WellCommerce\Bundle\CoreBundle\Twig\ImageExtension
        tags:
            - { name: twig.extension }
        arguments: ['@image.helper']

    twig.extension.mail:
        class: WellCommerce\Bundle\CoreBundle\Twig\MailExtension
        tags:
            - { name: twig.extension }
        arguments: ['@kernel']

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    knp.packagist_api.client:
        class: Packagist\Api\Client

    package.helper:
        class: WellCommerce\Bundle\CoreBundle\Helper\Package\PackageHelper
        arguments: ['@knp.packagist_api.client', '%kernel.root_dir%/installer']

    console.action_executor:
        class: WellCommerce\Bundle\CoreBundle\Console\Executor\ConsoleActionExecutor
        arguments: ['@kernel']

    doctrine_enhancer.cache_warmer:
        class: WellCommerce\Bundle\CoreBundle\CacheWarmer\DoctrineEnhancerCacheWarmer
        arguments: ['@doctrine.trait_generator.enhancer_collection']
        public: false
        tags:
            - { name: kernel.cache_warmer, priority: 1000 }

    bundle.cache_warmer:
        class: WellCommerce\Bundle\CoreBundle\CacheWarmer\BundleCacheWarmer
        arguments: ['@kernel']
        public: false
        tags:
            - { name: kernel.cache_warmer, priority: 1001 }
