WellCommerce\Bundle\CatalogBundle\Entity\ProducerCollectionRoute:
    type: entity
    cache:
        usage: NONSTRICT_READ_WRITE
    table: route_producer_collection
    manyToOne:
        identifier:
            targetEntity: WellCommerce\Bundle\CatalogBundle\Entity\ProducerCollection
            fetch: LAZY
            joinColumns:
                foreign_id:
                    referencedColumnName: id
                    onDelete: CASCADE
