# WellCommerce Open-Source E-Commerce Platform
#
# This file is part of the WellCommerce package.
# (c) Adam Piotrowski <adam@wellcommerce.org>
#
# For the full copyright and license information,
# please view the LICENSE file that was distributed with this source code.

admin.producer_collection.index:
    path: /index
    defaults:
        _controller: 'producer_collection.controller.admin:indexAction'
    options:
        require_admin_permission: producer_collection.index

admin.producer_collection.grid:
    path: /grid
    condition: "request.isXmlHttpRequest()"
    defaults:
        _controller: 'producer_collection.controller.admin:gridAction'
    options:
        expose: true
        require_admin_permission: producer_collection.index

admin.producer_collection.add:
    path: /add
    defaults:
        _controller: 'producer_collection.controller.admin:addAction'
    options:
        require_admin_permission: producer_collection.add

admin.producer_collection.edit:
    path: '/edit/{id}'
    defaults:
        _controller: 'producer_collection.controller.admin:editAction'
    options:
        expose: true
        require_admin_permission: producer_collection.edit

admin.producer_collection.delete:
    path: '/delete/{id}'
    defaults:
        _controller: 'producer_collection.controller.admin:deleteAction'
    options:
        expose: true
        require_admin_permission: producer_collection.delete

admin.producer_collection.delete_group:
    path: '/delete_group'
    defaults:
        _controller: 'producer_collection.controller.admin:deleteGroupAction'
    options:
        expose: true
        require_admin_permission: producer_collection.delete

admin.producer_collection.get_collections_by_producer_id.ajax.index:
    path: /ajaxGetCollectionsByProducer
    defaults:
        _controller: 'producer_collection.controller.admin:ajaxGetCollectionsByProducer'
    options:
        expose: true
        require_admin_permission: producer_collection.index